#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════╗
# ║  ANALYTICS DASHBOARD — Real-time Toolkit Metrics                  ║
# ╚══════════════════════════════════════════════════════════════════╝

set -e

TOOLKIT_DIR="${TOOLKIT_DIR:-$HOME/.openclaw/workspace/kimiclaw-toolkit}"
LOGS_DIR="$TOOLKIT_DIR/logs"
mkdir -p "$LOGS_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
RUN_ID=$(date -u +"%Y%m%d_%H%M%S")

echo "═══════════════════════════════════════════════════════════════"
echo "  KIMICLAW TOOLKIT — ANALYTICS DASHBOARD"
echo "  $TIMESTAMP"
echo "═══════════════════════════════════════════════════════════════"

# Count content generated
ARTICLES=$(ls -1 "$TOOLKIT_DIR/outputs/article_"*.md 2>/dev/null | wc -l)
SOCIAL=$(ls -1 "$TOOLKIT_DIR/outputs/social_"*.md 2>/dev/null | wc -l)
LEADMAGNETS=$(ls -1 "$TOOLKIT_DIR/outputs/leadmagnet_"*.md 2>/dev/null | wc -l)
EMAILS=$(ls -1 "$TOOLKIT_DIR/outputs/emails_"*.md 2>/dev/null | wc -l)
ANALYTICS=$(ls -1 "$TOOLKIT_DIR/outputs/analytics_"*.md 2>/dev/null | wc -l)
IMAGES=$(ls -1 "$TOOLKIT_DIR/images/image_"*.jpg 2>/dev/null | wc -l)

TOTAL_CONTENT=$((ARTICLES + SOCIAL + LEADMAGNETS + EMAILS + ANALYTICS + IMAGES))

# Count by niche
SAAS_COUNT=$(ls -1 "$TOOLKIT_DIR/outputs/"*saas* 2>/dev/null | wc -l)
ECOM_COUNT=$(ls -1 "$TOOLKIT_DIR/outputs/"*ecommerce* 2>/dev/null | wc -l)
FREELANCE_COUNT=$(ls -1 "$TOOLKIT_DIR/outputs/"*freelance* 2>/dev/null | wc -l)
HEALTH_COUNT=$(ls -1 "$TOOLKIT_DIR/outputs/"*health* 2>/dev/null | wc -l)
MUSIC_COUNT=$(ls -1 "$TOOLKIT_DIR/outputs/"*music-production* 2>/dev/null | wc -l)

# GitHub stats
GIT_COMMITS=$(cd "$HOME/.openclaw/workspace" && git rev-list --count HEAD 2>/dev/null || echo "0")
GIT_FILES=$(cd "$HOME/.openclaw/workspace" && git ls-files | wc -l 2>/dev/null || echo "0")

# Cron jobs
CRON_JOBS=$(crontab -l 2>/dev/null | grep -c "kimiclaw" || echo "0")

# Revenue tracker
REVENUE_FILE="$HOME/.openclaw/workspace/revenue/revenue-tracker.md"
if [ -f "$REVENUE_FILE" ]; then
    CURRENT_REVENUE=$(grep "Current Revenue:" "$REVENUE_FILE" | sed 's/.*\$//' | tr -d ' \n')
else
    CURRENT_REVENUE="0"
fi

# System health
DISK_USAGE=$(df -h / | awk 'NR==2 {print $5}')
MEMORY_USAGE=$(free | grep Mem | awk '{printf "%.0f", $3/$2 * 100}')
UPTIME=$(uptime -p 2>/dev/null || uptime | awk -F',' '{print $1}')

# Generate dashboard report
DASHBOARD_FILE="$LOGS_DIR/dashboard_${RUN_ID}.md"
cat > "$DASHBOARD_FILE" << EOF
# Kimiclaw Toolkit — Analytics Dashboard
**Generated:** $TIMESTAMP

## Content Production
| Metric | Count |
|--------|-------|
| SEO Articles | $ARTICLES |
| Social Media Packs | $SOCIAL |
| Lead Magnets | $LEADMAGNETS |
| Email Sequences | $EMAILS |
| Analytics Templates | $ANALYTICS |
| AI Images | $IMAGES |
| **TOTAL** | **$TOTAL_CONTENT** |

## Content by Niche
| Niche | Count |
|-------|-------|
| SaaS | $SAAS_COUNT |
| E-commerce | $ECOM_COUNT |
| Freelance | $FREELANCE_COUNT |
| Health | $HEALTH_COUNT |
| Music Production | $MUSIC_COUNT |

## GitHub Activity
| Metric | Value |
|--------|-------|
| Total Commits | $GIT_COMMITS |
| Tracked Files | $GIT_FILES |
| Repository | xsjass/kimiclaw-workspace |

## System Health
| Metric | Status |
|--------|--------|
| Disk Usage | $DISK_USAGE |
| Memory Usage | $MEMORY_USAGE% |
| Cron Jobs | $CRON_JOBS active |
| Uptime | $UPTIME |

## Revenue Tracker
| Metric | Value |
|--------|-------|
| Current Revenue | \$$CURRENT_REVENUE |
| Target | \$10,000 |
| Progress | $((CURRENT_REVENUE * 100 / 10000))% |
| Days Remaining | 29 |

## Limitations Status
| # | Limitation | Status |
|---|-----------|--------|
| 1 | Dependency on JJ's business | ✅ RESOLVED |
| 6 | Text-only output | ✅ RESOLVED |
| 7 | Single point of failure | ✅ RESOLVED |
| 3 | Payment collection | 🔴 BLOCKING |
| 4 | Reddit access | 🔴 BLOCKED |
| 5 | No phone number | 🟡 WORKAROUND |

## Next Actions
- [ ] Launch on Product Hunt (2026-05-10)
- [ ] Post on Hacker News
- [ ] Build Twitter auto-post integration
- [ ] Find payment collection method
- [ ] Reach 1,000 GitHub stars

---
*Auto-generated by Kimiclaw Analytics Module*
EOF

echo ""
echo "📊 CONTENT PRODUCTION"
echo "   Articles:        $ARTICLES"
echo "   Social Packs:    $SOCIAL"
echo "   Lead Magnets:    $LEADMAGNETS"
echo "   Email Sequences: $EMAILS"
echo "   Analytics:       $ANALYTICS"
echo "   AI Images:       $IMAGES"
echo "   ────────────────────────"
echo "   TOTAL:           $TOTAL_CONTENT deliverables"
echo ""
echo "💻 GITHUB"
echo "   Commits:         $GIT_COMMITS"
echo "   Files:           $GIT_FILES"
echo ""
echo "💰 REVENUE"
echo "   Current:         \$$CURRENT_REVENUE / \$10,000"
echo "   Progress:        $((CURRENT_REVENUE * 100 / 10000))%"
echo ""
echo "🖥️  SYSTEM"
echo "   Disk:            $DISK_USAGE"
echo "   Memory:          $MEMORY_USAGE%"
echo "   Cron Jobs:       $CRON_JOBS"
echo "   Uptime:          $UPTIME"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  DASHBOARD: $DASHBOARD_FILE"
echo "═══════════════════════════════════════════════════════════════"

# Log to master activity log
echo "[$TIMESTAMP] Dashboard | Content: $TOTAL_CONTENT | Revenue: \$$CURRENT_REVENUE | Commits: $GIT_COMMITS" >> "$LOGS_DIR/activity.log"
