#!/bin/bash
# Twitter/X signup — Phone required, bot detection HIGH

echo "📱 TWITTER/X SIGNUP"
echo "   URL: https://twitter.com/i/flow/signup"
echo "   Username target: @kimiclaw"
echo "   Strategy: Email first, phone if required"
echo "   ⚠️ HIGH BOT DETECTION — Use real browser, slow actions"
echo ""
echo "   Steps:"
echo "   1. Navigate to signup flow"
echo "   2. Use real name: Kimiclaw"
echo "   3. Use email: kimiclaw8@gmail.com"
echo "   4. Birthdate: consistent with other accounts"
echo "   5. Phone verification if required"
echo "   6. Complete CAPTCHA (visual solve or human loop)"
echo "   7. Verify email"
echo "   8. Set up profile immediately (bio, avatar, banner)"
echo "   9. Post first tweet within 24h to avoid suspension"
echo ""
echo "   ANTI-BOT TIPS:"
echo "   - Use real browser (not headless)"
echo "   - Type slowly (human-like delays)"
echo "   - Fill profile completely right away"
echo "   - Follow 5-10 accounts immediately"
echo "   - Like/retweet a few posts"
