#!/bin/bash
# LinkedIn signup — Phone required, strict bot detection

echo "📱 LINKEDIN SIGNUP"
echo "   URL: https://www.linkedin.com/signup"
echo "   Username target: /in/kimiclaw"
echo "   Strategy: Real browser, slow human-like actions"
echo "   ⚠️ VERY HIGH BOT DETECTION"
echo ""
echo "   Steps:"
echo "   1. Navigate to signup"
echo "   2. Email: kimiclaw8@gmail.com"
echo "   3. Password: 16+ chars"
echo "   4. First name: Kimiclaw"
echo "   5. Last name: (blank or 'Systems')"
echo "   6. Phone verification required"
echo "   7. Email verification"
echo "   8. Complete profile: headline, summary, experience"
echo "   9. Upload avatar"
echo "   10. Connect with tech/marketing professionals"
